import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ContactDetails, useQuote } from "@/components/site-shell";
import { PageCover, SectionHeading } from "@/components/page-elements";
import { site, pageHead } from "@/lib/site";
export const Route = createFileRoute("/about")({ head: () => pageHead("About Our Painting Artisans", "Meet Luxurious Professional Painting. Over 15 years of premium craftsmanship serving Toronto, GTA, York, Halton, Peel and Durham."), component: About });
function About() {
 const quote = useQuote();
 return <><PageCover eyebrow="About Us" title={<>Welcome to <span className="gold-text">Luxurious</span><br />Professional Painting</>} image={site.aboutImage} /><section className="section"><div className="container-lux split"><div className="split-image story-image"><img src={site.storyImage} alt="Elegant interior space" loading="lazy" /></div><div className="split-copy"><p className="eyebrow">Our Story</p><h2>We don't just paint walls — we elevate environments</h2><div className="prose">{site.story.map(text => <p key={text}>{text}</p>)}</div></div></div></section><section className="section section-alternate"><div className="container-lux"><SectionHeading eyebrow="What Drives Us" title="The principles behind every project" /><div className="principles">{[{ title: "Artistry", body: "Every project is treated as a masterpiece. Our artisans bring precision and flair to every stroke, from intricate interior details to grand exterior finishes." }, { title: "Premium Materials", body: "We use premium materials and cutting-edge techniques, ensuring enduring beauty and durability that stands the test of time." }, { title: "Customer Satisfaction", body: "Every project is a testament to our dedication to customer satisfaction. We work with you to bring your vision to life." }].map((item, index) => <article className="principle" key={item.title}><span className="principle-number">0{index + 1}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></div></section><section className="section"><div className="container-lux split"><div className="split-copy"><p className="eyebrow">Proudly Serving</p><h2>Toronto and the GTA</h2><div className="prose"><p>Based in Toronto, we proudly serve the local community and surrounding regions, bringing luxury painting to homes and businesses across the Greater Toronto Area.</p></div><div className="service-areas">{site.business.serviceAreas.map(area => <span key={area}>{area}</span>)}</div></div><div className="location-tool"><h3>Our Location</h3><ContactDetails /><Button variant="gold" onClick={() => quote()}>Request a Free Quote <ArrowRight /></Button></div></div></section></>;
}
