import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Clock, Mail, MapPin, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { QuoteForm } from "@/components/site-shell";
import { PageCover, SectionHeading } from "@/components/page-elements";
import { site, pageHead } from "@/lib/site";
export const Route = createFileRoute("/contact")({ head: () => pageHead("Contact & Free Painting Quote", "Contact Luxurious Professional Painting for your free quote. Call (437) 996-8087 or visit 10 Tuxedo Ct, Toronto, ON M1G 3S4."), component: Contact });
function Contact() {
 return <><PageCover eyebrow="Contact Us" title={<>Get Your <span className="gold-text">Free Quote</span></>} subtitle="Questions? Ready for a quote? We're here to help." image={site.contactHero} /><section className="section"><div className="container-lux contact-grid"><div className="contact-intro"><p className="eyebrow">Reach us directly</p><h2>Let's talk about your project</h2><p>Whether you're refreshing a single room or updating your property's facade, our team is ready to help. Reach out by phone, email, or the form — we'll get back to you shortly.</p><div className="contact-cards">{[{ Icon: Phone, label: "Phone", value: site.business.phone, href: `tel:${site.business.phoneRaw}` }, { Icon: Mail, label: "Email", value: site.business.email, href: `mailto:${site.business.email}` }, { Icon: MapPin, label: "Address", value: site.business.address }, { Icon: Clock, label: "Service Area", value: site.business.serviceAreas.join(", ") }].map(({ Icon, label, value, href }) => <div key={label} className="contact-card"><span className="trust-icon"><Icon size={20} /></span><div><small>{label}</small><p>{href ? <a href={href}>{value}</a> : value}</p></div></div>)}</div></div><div className="contact-form-tool"><QuoteForm contact /></div></div></section><section className="map-section"><div className="container-lux"><SectionHeading eyebrow="Find us" title="Proudly serving the local community" subtitle={site.business.address} /><Button asChild variant="luxLink"><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(site.business.address)}`} target="_blank" rel="noopener noreferrer">Open in Google Maps <ArrowRight /></a></Button></div></section></>;
}
