import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useQuote } from "@/components/site-shell";
import { PageCover, SectionHeading, SimpleCTA } from "@/components/page-elements";
import { site, pageHead } from "@/lib/site";
export const Route = createFileRoute("/services")({ head: () => pageHead("Painting & Decorating Services", "Explore indoor and outdoor painting, expert color consultancy, restoration, paint preparation, custom palettes, 3D previews, paint mixing and wallpaper selection."), component: Services });
function Services() {
 const quote = useQuote();
 return <><PageCover eyebrow="Our Services" title={<>Painting & Decorating<br /><span className="gold-text">Done right</span></>} subtitle="A comprehensive range of in-store and in-home services to meet your painting and decorating needs." image={site.servicesHero} /><section className="section"><div className="container-lux"><SectionHeading eyebrow="In-Home Services" title="Transform your living spaces" subtitle="Comprehensive in-home painting and decorating services committed to delivering exceptional results that elevate the aesthetic appeal of your interiors and exteriors." /><div className="service-list">{site.services.filter(service => service.category === "In-Home").map(service => <article className="service-row" key={service.id} id={service.id}><img className="service-photo" src={service.image} alt={service.title} loading="lazy" /><div><p className="eyebrow">{service.category}</p><h3>{service.title}</h3><p>{service.description}</p><div className="service-summary"><Check size={16} /><span>{service.summary}</span></div><Button variant="luxLink" onClick={() => quote(service.title)}>Request a quote <ArrowRight /></Button></div></article>)}</div></div></section><section className="section section-alternate"><div className="container-lux"><SectionHeading eyebrow="In-Store Services" title="Everything you need, in-store" subtitle="From custom color mixing to wallpaper selection and 3D rendering previews, our team is dedicated to providing high-quality products and exceptional customer service." /><div className="store-services">{site.services.filter(service => service.category === "In-Store").map(service => <article className="store-service" key={service.id}><img src={service.image} alt={service.title} loading="lazy" /><div><h3>{service.title}</h3><p>{service.description}</p></div></article>)}</div></div></section><SimpleCTA title="Ready to begin?" description="Call us for your free quote, or send a message and we'll get back to you shortly." /></>;
}
